### ISSUE TITLE
component - save and cancel buttons in pagetitle

### ISSUE THREAD

**Issue by genesisfan** [thotmx/Efemerides#1]
Hi Hermes,
In the Efemerides component New, the pagetitle only shows the Cancel button and not the Save button?

Efemerides component 0.9(b)
J!2.5.4
PHP 5.3.10

regards,
Marcel - www.genesisfan.net

**Comment by thotmx** [comment]
The save button is on the bottom zone.

**Comment by thotmx** [comment]
I'll close this issue because the buttons exist.
