### ISSUE TITLE
Efemerides Module style output

### ISSUE THREAD

**Issue by genesisfan** [thotmx/Efemerides#4]
Hi Hermes,
The Efemerides module style output is not what I like, e.g.

date
title
description
link to the event
show all the events

How can I create this e.g. (I'm not a CSS wizzkid ;-) :

date, title1
description1, link to the event

date, title2
description2, link to the event

show all the events

Efemerides module 0.9(b)
J!2.5.4
PHP 5.3.10

regards,
Marcel - www.genesisfan.net

**Comment by thotmx** [comment]
You can change the CSS style in the administrator

**Comment by thotmx** [comment]
I think that this is not relevant. Because there is a way to do that on the administrator component.
